name: Latest Bitcoin Core

on:
  workflow_dispatch: # Build can be triggered manually from github.com
  pull_request: 

permissions:
  contents: read

jobs:

  regression-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout eclair
        uses: actions/checkout@v4
        with:
          path: eclair

      - name: Pull bitcoind from docker image
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          docker pull pinheadmz/bitcoin:pr35182-ddefe4263b
          cid=$(docker create pinheadmz/bitcoin:pr35182-ddefe4263b)
          docker cp $cid:/opt/bin/bitcoind   $GITHUB_WORKSPACE/bin/bitcoind
          docker cp $cid:/opt/bin/bitcoin-cli $GITHUB_WORKSPACE/bin/bitcoin-cli
          docker rm $cid
          chmod +x $GITHUB_WORKSPACE/bin/*
          sudo apt-get update -y
          sudo apt-get install -y libevent-dev libboost-dev libzmq3-dev libsqlite3-dev
          $GITHUB_WORKSPACE/bin/bitcoind -version

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Configure OS settings
        run: echo "fs.file-max = 1024000" | sudo tee -a /etc/sysctl.conf

      - name: Run eclair tests
        run: BITCOIND_DIR=$GITHUB_WORKSPACE/bin ./mvnw test -DtagsToExclude=external-api
        working-directory: ./eclair
